# Generated by Django 3.0.7 on 2020-06-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='replays',
        ),
        migrations.AddField(
            model_name='replay',
            name='replays',
            field=models.ManyToManyField(to='replay.Tag'),
        ),
    ]
