# Generated by Django 3.0.7 on 2020-06-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0003_auto_20200625_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replay',
            old_name='replays',
            new_name='tags',
        ),
    ]
