# Generated by Django 3.0.7 on 2020-06-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0005_auto_20200625_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='replay',
            name='case_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='replay',
            name='plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='replay',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
