# Generated by Django 3.0.7 on 2020-06-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0006_auto_20200626_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='principle',
            field=models.TextField(blank=True),
        ),
    ]
