# Generated by Django 3.0.7 on 2020-06-27 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0007_replay_principle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='replay.Cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='replay.Cycle')),
            ],
        ),
        migrations.CreateModel(
            name='RoadBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='replay.Cycle')),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='replay.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='Execute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='replay.Cycle')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnoseRootCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='replay.Cycle')),
                ('road_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='replay.RoadBlock')),
            ],
        ),
    ]
