# Generated by Django 3.0.7 on 2020-06-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0008_cycle_diagnoserootcase_execute_goal_roadblock_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadblock',
            name='cycle',
        ),
    ]
