# Generated by Django 3.0.7 on 2020-06-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0010_auto_20200627_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='title',
            new_name='goal',
        ),
        migrations.RemoveField(
            model_name='execute',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='roadblock',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='rootcase',
            name='road_block',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='cycle',
        ),
        migrations.AddField(
            model_name='cycle',
            name='blocks',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='cycle',
            name='execute',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='root_case',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='cycle',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
