# Generated by Django 3.0.7 on 2020-06-28 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelpart',
            name='next_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flywheel.WheelPart'),
        ),
    ]
