# Generated by Django 3.1 on 2020-08-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0003_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flywheel',
            name='rate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='flywheel',
            name='rate_one_year',
            field=models.IntegerField(default=0),
        ),
    ]
