# Generated by Django 3.1 on 2020-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0006_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='principle',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('good', 'good'), ('bad', 'bad')], default='good', max_length=20),
        ),
    ]
