# Generated by Django 3.1 on 2020-09-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0008_auto_20200902_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='recount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='solution_long',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='solution_middle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='solution_short',
            field=models.TextField(blank=True),
        ),
    ]
