# Generated by Django 3.1 on 2020-09-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0009_auto_20200904_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='sys_level',
            field=models.IntegerField(choices=[(3, '高'), (2, '中'), (1, '低')], default=0),
            preserve_default=False,
        ),
    ]
