# Generated by Django 3.1 on 2020-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0011_auto_20200904_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='flywheel',
            name='status',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=200),
        ),
        migrations.AlterField(
            model_name='flywheel',
            name='best',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='flywheel',
            name='worse',
            field=models.CharField(default='', max_length=200),
        ),
    ]
