# Generated by Django 3.1 on 2020-09-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0012_auto_20200904_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flywheel',
            new_name='Copy',
        ),
        migrations.AlterModelTable(
            name='copy',
            table='flywheel_flywheel',
        ),
    ]
