# Generated by Django 3.1 on 2020-09-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0013_auto_20200904_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='best',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='worse',
        ),
    ]
