# Generated by Django 3.1 on 2020-09-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0014_auto_20200904_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='can_copy',
            field=models.BooleanField(default=False),
        ),
    ]
