# Generated by Django 3.1 on 2020-09-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0015_case_can_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='cost',
            field=models.TextField(),
        ),
    ]
