# Generated by Django 3.1 on 2020-09-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0016_auto_20200905_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('good', '成功案例'), ('bad', '失败案例')], default='good', max_length=20),
        ),
    ]
