# Generated by Django 3.1 on 2020-09-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0018_auto_20200914_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='cost',
            new_name='depend',
        ),
        migrations.AlterField(
            model_name='case',
            name='principle',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='solution_long',
            field=models.TextField(blank=True, help_text='如何防火'),
        ),
        migrations.AlterField(
            model_name='case',
            name='solution_middle',
            field=models.TextField(blank=True, help_text='如何控火'),
        ),
        migrations.AlterField(
            model_name='case',
            name='solution_short',
            field=models.TextField(blank=True, help_text='如何灭火'),
        ),
    ]
