# Generated by Django 3.1 on 2020-09-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0020_auto_20200917_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='copy',
            field=models.ForeignKey(help_text='copy到哪了', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flywheel.copy'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='how',
            field=models.TextField(blank=True, default='', help_text='如何做'),
        ),
    ]
