# Generated by Django 3.1 on 2020-09-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0021_auto_20200917_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='depends',
            field=models.ManyToManyField(to='flywheel.Copy'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='how',
            field=models.TextField(blank=True, default='', help_text='如何做，请从最坏到最好依次兜底'),
        ),
    ]
