# Generated by Django 3.1 on 2020-09-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0024_auto_20200918_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='depends',
            new_name='downstreams',
        ),
    ]
