# Generated by Django 3.1 on 2020-09-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0026_auto_20200918_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='analyze',
            field=models.TextField(blank=True, help_text='分析问题'),
        ),
        migrations.AddField(
            model_name='goal',
            name='execution',
            field=models.TextField(blank=True, help_text='执行'),
        ),
        migrations.AddField(
            model_name='goal',
            name='problems',
            field=models.TextField(blank=True, help_text='发现问题'),
        ),
        migrations.AddField(
            model_name='goal',
            name='solution',
            field=models.TextField(blank=True, help_text='方案'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='depends',
            field=models.ManyToManyField(blank=True, related_name='downstreams', to='flywheel.Copy'),
        ),
    ]
