# Generated by Django 3.1 on 2020-09-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0031_auto_20200918_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='situation',
            field=models.TextField(blank=True, help_text='背景'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='solution',
            field=models.TextField(blank=True, help_text='方案（倒推，从大目标推到小目标，或者说将大目标拆解成小目标）'),
        ),
    ]
