# Generated by Django 3.1 on 2020-09-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flywheel', '0032_auto_20200920_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='type',
            field=models.CharField(choices=[('知道', '知道'), ('悟道', '悟道'), ('得道', '得到')], default='知道', max_length=200),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off'), ('focus', 'focus')], default='off', max_length=200),
        ),
    ]
